---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangweijian.
--- DateTime: 2025/5/8 11:26
---
local now=tonumber(ARGV[1])
local rate=tonumber(ARGV[2])
redis.call('ZREMRANGEBYSCORE',KEYS[1],'-inf',now-1)
local last=redis.call('ZRANGE',KEYS[1],-1,-1)
local next_time=now
if #last > 0 then
    next_time=tonumber(last[1])+1/rate
end
if now > next_time then
    next_time=now
end
redis.call('ZADD',KEYS[1],next_time,tostring(next_time))
return tostring(next_time-now)