---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangweijian.
--- DateTime: 2025/5/8 11:42
---
local limit=tonumber(ARGV[1])
local window=tonumber(ARGV[2])
local now=tonumber(ARGV[3])
redis.call('ZREMRANGEBYSCORE',KEYS[1],'-inf',now-window)
local count=redis.call('ZCARD',KEYS[1])
if count<limit then
    redis.call('ZADD',KEYS[1],now,tostring(now))
    return 1
else
    return 0
end